import { ThemeConfig } from './types';

export const THEMES: Record<string, ThemeConfig> = {
  cyber: {
    id: 'cyber',
    name: 'Cyber Synth',
    emoji: '👾',
    description: 'Cyberpunk aesthetics with violet neon, modern rounded corners, and impactful glows.',
    bgClass: 'bg-[#0b0c10] bg-cyber-grid text-[#c5c6c7] min-h-screen transition-colors duration-500 selection:bg-indigo-500 selection:text-white',
    textClass: 'text-indigo-400',
    textMutedClass: 'text-gray-400',
    cardClass: 'bg-[#1f2833]/80 backdrop-blur-md border border-[#45f3ff]/30 rounded-2xl shadow-[0_0_15px_rgba(69,243,255,0.1)] hover:shadow-[0_0_25px_rgba(69,243,255,0.25)] hover:border-[#45f3ff]/80 transition-all duration-300',
    cardHeaderClass: 'border-b border-[#45f3ff]/10 pb-4',
    badgeClass: {
      Game: 'bg-slate-950/90 text-emerald-400 border border-emerald-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      DLC: 'bg-slate-950/90 text-purple-400 border border-purple-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      Loot: 'bg-slate-950/90 text-amber-400 border border-amber-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      Beta: 'bg-slate-950/90 text-cyan-400 border border-cyan-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      EarlyAccess: 'bg-slate-950/90 text-rose-400 border border-rose-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      default: 'bg-slate-950/90 text-gray-400 border border-gray-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm'
    },
    buttonPrimaryClass: 'bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-black font-bold py-1.5 px-4 rounded-lg shadow-[0_0_10px_rgba(6,182,212,0.3)] transition-all duration-300 hover:scale-[1.02] active:scale-[0.98] font-space text-center block w-full text-xs md:text-sm',
    buttonSecondaryClass: 'bg-gray-800 hover:bg-gray-700 text-white font-semibold py-1.5 px-3 rounded-lg border border-gray-700 transition-all text-xs',
    inputClass: 'bg-[#1f2833] border border-[#45f3ff]/20 text-[#45f3ff] focus:border-[#45f3ff] focus:ring-1 focus:ring-[#45f3ff] rounded-lg px-3 py-1.5 outline-none transition-all text-xs md:text-sm',
    accentBorderClass: 'border-indigo-500',
    glowClass: 'text-[#45f3ff] drop-shadow-[0_0_10px_rgba(69,243,255,0.6)]',
    fontFamily: 'font-sans',
    titleFontFamily: 'font-space tracking-tight font-bold',
  },
  neonblue: {
    id: 'neonblue',
    name: 'Neon Blue',
    emoji: '⚡',
    description: 'Futuristic dark atmosphere dominated by electric neon blue tones and deep shadows.',
    bgClass: 'bg-[#020617] text-slate-100 min-h-screen transition-colors duration-500 selection:bg-blue-600 selection:text-white',
    textClass: 'text-blue-400',
    textMutedClass: 'text-slate-400',
    cardClass: 'bg-slate-900/70 backdrop-blur-md border border-blue-500/30 rounded-xl hover:border-blue-400 hover:shadow-[0_0_15px_rgba(59,130,246,0.3)] transition-all duration-300 shadow-lg',
    cardHeaderClass: 'border-b border-blue-500/10 pb-4',
    badgeClass: {
      Game: 'bg-slate-950/90 text-emerald-400 border border-emerald-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      DLC: 'bg-slate-950/90 text-indigo-400 border border-indigo-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      Loot: 'bg-slate-950/90 text-amber-400 border border-amber-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      Beta: 'bg-slate-950/90 text-blue-400 border border-blue-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      EarlyAccess: 'bg-slate-950/90 text-rose-400 border border-rose-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      default: 'bg-slate-950/90 text-slate-400 border border-slate-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm'
    },
    buttonPrimaryClass: 'bg-blue-600 hover:bg-blue-500 text-white font-bold py-1.5 px-4 rounded-lg shadow-[0_0_10px_rgba(59,130,246,0.4)] transition-all duration-300 hover:scale-[1.02] active:scale-[0.98] font-sans text-center block w-full text-xs md:text-sm',
    buttonSecondaryClass: 'bg-slate-800 hover:bg-slate-700 text-blue-400 font-semibold py-1.5 px-3 rounded-lg border border-blue-500/20 transition-all text-xs',
    inputClass: 'bg-slate-950/80 border border-blue-500/30 text-blue-100 focus:border-blue-400 focus:ring-1 focus:ring-blue-400 rounded-lg px-3 py-1.5 outline-none transition-all text-xs md:text-sm',
    accentBorderClass: 'border-blue-400',
    glowClass: 'text-blue-400 drop-shadow-[0_0_8px_rgba(59,130,246,0.6)]',
    fontFamily: 'font-sans',
    titleFontFamily: 'font-sans font-extrabold tracking-tight',
  },
  neongreen: {
    id: 'neongreen',
    name: 'Neon Green',
    emoji: '🟢',
    description: 'Hacker and Matrix style, pitch black background with bright high-luminosity neon green details.',
    bgClass: 'bg-[#030712] text-zinc-100 min-h-screen transition-colors duration-500 selection:bg-emerald-600 selection:text-white',
    textClass: 'text-emerald-400',
    textMutedClass: 'text-zinc-400',
    cardClass: 'bg-zinc-950/80 backdrop-blur-md border border-emerald-500/30 rounded-xl hover:border-emerald-400 hover:shadow-[0_0_15px_rgba(16,185,129,0.3)] transition-all duration-300 shadow-lg',
    cardHeaderClass: 'border-b border-emerald-500/10 pb-4',
    badgeClass: {
      Game: 'bg-zinc-950/90 text-emerald-400 border border-emerald-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      DLC: 'bg-zinc-950/90 text-purple-400 border border-purple-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      Loot: 'bg-zinc-950/90 text-amber-400 border border-amber-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      Beta: 'bg-zinc-950/90 text-cyan-400 border border-cyan-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      EarlyAccess: 'bg-zinc-950/90 text-rose-400 border border-rose-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      default: 'bg-zinc-950/90 text-zinc-400 border border-zinc-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm'
    },
    buttonPrimaryClass: 'bg-emerald-600 hover:bg-emerald-500 text-white font-bold py-1.5 px-4 rounded-lg shadow-[0_0_10px_rgba(16,185,129,0.4)] transition-all duration-300 hover:scale-[1.02] active:scale-[0.98] font-sans text-center block w-full text-xs md:text-sm',
    buttonSecondaryClass: 'bg-zinc-900 hover:bg-zinc-800 text-emerald-400 font-semibold py-1.5 px-3 rounded-lg border border-emerald-500/20 transition-all text-xs',
    inputClass: 'bg-zinc-950 border border-emerald-500/30 text-emerald-100 focus:border-emerald-400 focus:ring-1 focus:ring-emerald-400 rounded-lg px-3 py-1.5 outline-none transition-all text-xs md:text-sm',
    accentBorderClass: 'border-emerald-400',
    glowClass: 'text-emerald-400 drop-shadow-[0_0_8px_rgba(16,185,129,0.6)]',
    fontFamily: 'font-sans',
    titleFontFamily: 'font-sans font-extrabold tracking-tight',
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset Warmth',
    emoji: '🌅',
    description: 'Warm sunset colors, cozy peach and terracotta palette with elegant dark accents.',
    bgClass: 'bg-[#faf6f0] text-stone-800 min-h-screen transition-colors duration-500 selection:bg-[#e06d53] selection:text-white',
    textClass: 'text-[#e06d53]',
    textMutedClass: 'text-stone-500',
    cardClass: 'bg-[#fffdfa] border-2 border-stone-200 rounded-3xl shadow-brutalist-warm hover:shadow-brutalist-warm-hover hover:border-[#e06d53]/80 transition-all duration-300',
    cardHeaderClass: 'border-b-2 border-stone-100 pb-4',
    badgeClass: {
      Game: 'bg-emerald-50 text-emerald-800 border-2 border-emerald-200 font-sans text-xs font-bold px-2.5 py-0.5 rounded-full',
      DLC: 'bg-indigo-50 text-indigo-800 border-2 border-indigo-200 font-sans text-xs font-bold px-2.5 py-0.5 rounded-full',
      Loot: 'bg-amber-50 text-amber-800 border-2 border-amber-200 font-sans text-xs font-bold px-2.5 py-0.5 rounded-full',
      Beta: 'bg-orange-50 text-orange-800 border-2 border-orange-200 font-sans text-xs font-bold px-2.5 py-0.5 rounded-full',
      EarlyAccess: 'bg-pink-50 text-pink-800 border-2 border-pink-200 font-sans text-xs font-bold px-2.5 py-0.5 rounded-full',
      default: 'bg-stone-50 text-stone-700 border-2 border-stone-200 font-sans text-xs font-bold px-2.5 py-0.5 rounded-full'
    },
    buttonPrimaryClass: 'bg-[#e06d53] hover:bg-[#c9573f] text-white font-bold py-1.5 px-4 rounded-xl shadow-md transition-all hover:scale-[1.02] active:scale-[0.98] font-outfit text-center block w-full text-xs md:text-sm',
    buttonSecondaryClass: 'bg-stone-100 hover:bg-stone-200 text-stone-700 font-bold py-1.5 px-3 rounded-xl transition-all border border-stone-200 text-xs',
    inputClass: 'bg-white border-2 border-stone-200 text-stone-800 focus:border-[#e06d53] focus:ring-0 rounded-xl px-3 py-1.5 outline-none transition-all shadow-sm text-xs md:text-sm',
    accentBorderClass: 'border-[#e06d53]',
    glowClass: 'text-[#e06d53]',
    fontFamily: 'font-sans',
    titleFontFamily: 'font-outfit font-extrabold tracking-tight',
  },
  vhs80s: {
    id: 'vhs80s',
    name: 'VHS 80s (Retro)',
    emoji: '📼',
    description: 'Vintage 80s aesthetic with synthwave grid, neon lettering, CRT scrolling, and brutalist shadows.',
    bgClass: 'bg-[#120024] bg-retro-grid text-[#ff007f] min-h-screen transition-colors duration-500 selection:bg-[#00ffff] selection:text-black vhs-noise relative overflow-hidden',
    textClass: 'text-[#00ffff] neon-glow-cyan',
    textMutedClass: 'text-[#b915d3]',
    cardClass: 'bg-[#21003d]/90 border-2 border-[#ff007f] rounded-none shadow-brutalist-vhs hover:shadow-brutalist-vhs-hover transition-all duration-200',
    cardHeaderClass: 'border-b-2 border-[#ff007f]/40 pb-4',
    badgeClass: {
      Game: 'bg-black text-[#39ff14] border-2 border-[#39ff14] font-mono text-[10px] uppercase tracking-wider px-2 py-0.5 rounded-none',
      DLC: 'bg-black text-[#ff007f] border-2 border-[#ff007f] font-mono text-[10px] uppercase tracking-wider px-2 py-0.5 rounded-none',
      Loot: 'bg-black text-[#ffff00] border-2 border-[#ffff00] font-mono text-[10px] uppercase tracking-wider px-2 py-0.5 rounded-none',
      Beta: 'bg-black text-[#00ffff] border-2 border-[#00ffff] font-mono text-[10px] uppercase tracking-wider px-2 py-0.5 rounded-none',
      EarlyAccess: 'bg-black text-[#f500ff] border-2 border-[#f500ff] font-mono text-[10px] uppercase tracking-wider px-2 py-0.5 rounded-none',
      default: 'bg-black text-white border-2 border-white font-mono text-[10px] uppercase tracking-wider px-2 py-0.5 rounded-none'
    },
    buttonPrimaryClass: 'bg-transparent hover:bg-[#ff007f] text-[#ff007f] hover:text-white border-2 border-[#ff007f] font-mono font-bold py-1.5 px-4 rounded-none shadow-none uppercase tracking-widest text-center transition-all duration-150 hover:translate-x-0.5 hover:translate-y-0.5 block w-full text-xs',
    buttonSecondaryClass: 'bg-black text-[#00ffff] border border-[#00ffff] font-mono py-1.5 px-3 rounded-none hover:bg-[#00ffff] hover:text-black transition-all uppercase text-[10px]',
    inputClass: 'bg-black border-2 border-[#ff007f] text-[#00ffff] focus:border-[#00ffff] focus:ring-0 rounded-none px-3 py-1.5 outline-none font-mono transition-all uppercase text-xs',
    accentBorderClass: 'border-[#ff007f]',
    glowClass: 'text-[#ff007f] neon-glow-pink font-mono tracking-widest',
    fontFamily: 'font-mono',
    titleFontFamily: 'font-mono uppercase font-bold tracking-widest',
  },
  space: {
    id: 'space',
    name: 'Constellation Space',
    emoji: '🌌',
    description: 'Deep galactic atmosphere with shooting stars, purple nebulae, and moving linked constellations.',
    bgClass: 'bg-[#03001e] text-slate-100 min-h-screen transition-colors duration-500 selection:bg-purple-600 selection:text-white relative overflow-hidden',
    textClass: 'text-cyan-400',
    textMutedClass: 'text-slate-400',
    cardClass: 'bg-slate-950/60 backdrop-blur-md border border-cyan-500/30 rounded-xl hover:border-purple-400 hover:shadow-[0_0_18px_rgba(168,85,247,0.3)] transition-all duration-300 shadow-lg',
    cardHeaderClass: 'border-b border-cyan-500/10 pb-4',
    badgeClass: {
      Game: 'bg-slate-950/90 text-emerald-400 border border-emerald-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      DLC: 'bg-slate-950/90 text-indigo-400 border border-indigo-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      Loot: 'bg-slate-950/90 text-amber-400 border border-amber-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      Beta: 'bg-slate-950/90 text-cyan-400 border border-cyan-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      EarlyAccess: 'bg-slate-950/90 text-rose-400 border border-rose-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm',
      default: 'bg-slate-950/90 text-slate-400 border border-slate-500/60 font-mono text-xs font-bold px-2.5 py-1 rounded-full backdrop-blur-sm'
    },
    buttonPrimaryClass: 'bg-gradient-to-r from-cyan-500 via-blue-600 to-purple-600 hover:from-cyan-400 hover:to-purple-500 text-white font-bold py-1.5 px-4 rounded-lg shadow-[0_0_12px_rgba(168,85,247,0.4)] transition-all duration-300 hover:scale-[1.02] active:scale-[0.98] font-sans text-center block w-full text-xs md:text-sm',
    buttonSecondaryClass: 'bg-slate-900 hover:bg-slate-800 text-cyan-400 font-semibold py-1.5 px-3 rounded-lg border border-cyan-500/20 transition-all text-xs',
    inputClass: 'bg-slate-950/80 border border-cyan-500/30 text-cyan-100 focus:border-purple-400 focus:ring-1 focus:ring-purple-400 rounded-lg px-3 py-1.5 outline-none transition-all text-xs md:text-sm',
    accentBorderClass: 'border-cyan-400',
    glowClass: 'text-cyan-400 drop-shadow-[0_0_8px_rgba(34,211,238,0.6)]',
    fontFamily: 'font-sans',
    titleFontFamily: 'font-sans font-extrabold tracking-tight',
  }
};
